name: Setup NodeJS
description: 'Setup NodeJS'
inputs:
  node-version: # id of input
    description: 'Version of node to use'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
