name: CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Clean install
        run: yarn ci

      # - name: Install dependencies
      #   run: yarn

      #     - name: Lint
      #       run: yarn lint:fix

      #     - name: Test
      #       run: yarn test

      # - name: Build
      #   run: yarn build
      - name: Semantic Release (Only branch "main")
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
      issues: read

  # deploy-dev:
  #   needs: [build]
  #   if: github.ref == 'refs/heads/dev'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger webhook
  #       run: |
  #         URL="${{ secrets.DEPLOY_DEV_WEBHOOK_URL }}"
  #         curl -X POST -d {} "$URL" -H "Content-Type:application/json"

  # deploy-main:
  #   needs: [build]
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger webhook
  #       run: |
  #         URL="${{ secrets.DEPLOY_MAIN_WEBHOOK_URL }}"
  #         curl -X POST -d {} "$URL" -H "Content-Type:application/json"

  # deploy-corp-somdet-main:
  #   needs: [build]
  #   if: github.ref == 'refs/heads/corp/somdet/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger webhook
  #       run: |
  #         URL="${{ secrets.DEPLOY_CORP_SOMDET_MAIN_WEBHOOK_URL }}"
  #         curl -X POST -d {} "$URL" -H "Content-Type:application/json"

  # deploy-corp-chula-main:
  #   needs: [build]
  #   if: github.ref == 'refs/heads/corp/chula/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger webhook
  #       run: |
  #         URL="${{ secrets.DEPLOY_CORP_CHULA_MAIN_WEBHOOK_URL }}"
  #         curl -X POST -d {} "$URL" -H "Content-Type:application/json"

  # deploy-corp-navy-main:
  #   needs: [build]
  #   if: github.ref == 'refs/heads/corp/navy/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger webhook
  #       run: |
  #         URL="${{ secrets.DEPLOY_CORP_NAVY_MAIN_WEBHOOK_URL }}"
  #         curl -X POST -d {} "$URL" -H "Content-Type:application/json"
