# name: Semantic Test
# on:
#   push:
#     branches:
#       - '*'

# jobs:
#   semantic:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Commit
#         uses: actions/checkout@v3
#       - name: Setup NodeJS
#         uses: ./.github/actions/setup-node

#       - name: Run Semantic Tests
#         run: yarn test:semantic
#       - name: Store Artifacts From Failed Tests
#         if: failure()
#         uses: actions/upload-artifact@v2
#         with:
#           name: test-results
#           path: test-results/
#           retention-days: 7
